### ISSUE TITLE
3D Time-lapse

### ISSUE THREAD

**Issue by LuisFMCuriel** [guiwitz/naparimovie#5]
Hello,

First of all, thank you for this amazing tool, it has become one of my favorite 3D animation tools. I have one question though, I want to use a script to animate a 3D time-lapse but I am not sure how to move to the next 3D frame using the script.

This is my script:
```
From frame 0 to frame 20
-rotate by 180 degrees around (1,0,0)
From frame 21 to frame 40
-rotate by 180 degrees around (0,0,1)
From frame 40 to frame 60
-rotate by 180 degrees around (1,0,0)
From frame 60 to frame 80
-rotate by 180 degrees around (0,0,1)
```

How can I include the time axis? or the other 3d frames?

Thanks in advance!

**Comment by guiwitz** [comment]
Hi, thanks for kind words!

As far as I can remember you can use the ```shift time by x``` command to move across time (as described here: https://github.com/guiwitz/naparimovie#script-based-key-frames). You can also find an example here https://github.com/guiwitz/naparimovie/blob/master/examples/moviecommands2.txt

Just FYI, naparimovie has become the [napari-animation plugin](https://github.com/napari/napari-animation). The 3Dscript part of naparimovie is not implemented there but you can use other scripting commands to create animations: https://github.com/napari/napari-animation#headless. If there's interest, I might however try to add these 3Dscript commands to the new plugin.

**Comment by LuisFMCuriel** [comment]
Oh, I see. Sorry to ask such a simple question. Anyway, thank you so much for the tool and the time you invest in it, people like you really make our lives much easier.  Thanks again!
